import type { APIContext } from "astro";

export function GET(context: APIContext) {
  const origin = context.site?.origin ?? new URL(context.url).origin;

  return new Response(
    `User-agent: *
Allow: /

# Block typical crawl waste
Disallow: /api/
Disallow: /_image
Disallow: /_astro/

# Sitemap is generated by @astrojs/sitemap on every build
Sitemap: ${origin}/sitemap.xml
Sitemap: ${origin}/sitemap-index.xml
`,
    {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
      },
    },
  );
}
